"""Add hub_state to M365Credential

Revision ID: 4cba8e0961c7
Revises: c0b53a85a807
Create Date: 2026-06-22 04:01:46.858688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cba8e0961c7'
down_revision: Union[str, Sequence[str], None] = 'c0b53a85a807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('m365_credentials', sa.Column('hub_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('m365_credentials', 'hub_state')
    # ### end Alembic commands ###
